apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: gcc 
spec:
  containers:
  - name: fedora-37
    image: fedora-37:latest
    command:
    - cat
    tty: true
    #capabilities:
    #  add: ["CAP_AUDIT_WRITE"]
